---
title: "Concatenate and export statistics to excel"
output: html_document
date: "`r Sys.Date()`"
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This notebook concatenate statistical results into a big table for:
- the comparisons across trials with different spheroids
- the comparisons across AR=1.3 clusters.



## Load libraries
```{r}
library(openxlsx)
library('tidyverse')
```


## Set up path
```{r}
main_path = "~/code_git/porpoise_spheroid"
stat_path = file.path(main_path, "stat")
```


## Functions
```{r}
rename_estimate_ratio = function(df){
  if("estimate" %in% colnames(df)){
      df = df %>% rename("estimate.or.ratio" = "estimate")
  }
  if("ratio" %in% colnames(df)){
      df = df %>% rename("estimate.or.ratio" = "ratio")
  }
  return(df)
}
```

```{r}
get_p_star = function(p_val){
  if(p_val <= 0.0001){
    p_star = "****"
  } else if (p_val <= 0.001){
    p_star = "***"
  } else if (p_val <= 0.01){
    p_star = "**"
  } else if (p_val <= 0.05){
    p_star = "*"
  } else {
    p_star = "ns"
  }
  return(p_star)
}
```


## Comparison across spheroids

### TC vs CT comparisons
```{r}
spheroid_position_list = list(
  "A_pos_decision_time" =             "ARall_A_decision_time_position_contrast.csv",
  "B_pos_decision_dist_sphere" =      "ARall_B1_decision_range_target_position_contrast.csv",
  "B_pos_decision_dist_spheroid" =    "ARall_B2_decision_range_clutter_position_contrast.csv",
  "C_pos_buzz_time" =                 "ARall_C_buzz_time_position_contrast.csv",
  "D_pos_buzz_range" =                "ARall_D_buzz_range_position_contrast.csv",
  "pos_scan_combind" =                "ARall_scan_combined_position_contrast.csv"
)
```

```{r}
for (f in names(spheroid_position_list)) {
  print(sprintf("Sheet %s: %s", f, spheroid_position_list[[f]]))
   df = read.csv(
    file=paste(stat_path, spheroid_position_list[[f]], sep="/")
  )
  spheroid_position_list[[f]] = rename_estimate_ratio(df) %>%
    add_column("p.annotation" = apply(df["p.value"], MARGIN = 1, FUN = get_p_star))
}

df_all = bind_rows(spheroid_position_list) %>%
  add_column(
    fig.panel = c(
      "Fig. S5A", "Fig. S5B left", "Fig. S5B right",
      "Fig. S5C", "Fig. S5D", "Fig. S4"
    ), .before = "contrast"
  ) %>%
  rename("Fig panel" = "fig.panel",
         "Contrast" = "contrast",
         "Estimate or ratio" = "estimate.or.ratio",
         "Lower CL" = "lower.CL",
         "Upper CL" = "upper.CL",
         "T ratio" = "t.ratio",
         "P value" = "p.value",
         "Fig annotation" = "p.annotation")

out_file = file.path(stat_path, "cmp_ARall_position.xlsx")
write.xlsx(df_all, file = out_file)
print(sprintf("Outputs written to %s", out_file))
```


### AR comparisons
```{r}
spheroid_AR_list = list(
  "A_sph_decision_time" =             "ARall_A_decision_time_spheroid_contrast.csv",
  "B_sph_decision_dist_to_sphere" =   "ARall_B1_decision_range_target_spheroid_contrast.csv",
  "B_sph_decision_dist_to_spheroid" = "ARall_B2_decision_range_clutter_spheroid_contrast.csv",
  "C_sph_buzz_time" =                 "ARall_C_buzz_time_spheroid_contrast.csv",
  "D_sph_buzz_range" =                "ARall_D_buzz_range_spheroid_contrast.csv",
  "sph_scan_combined" =               "ARall_scan_combined_spheroid_contrast.csv"
)
```

```{r}
stat_spheroid_panel = list(
  "A_sph_decision_time" =             "Fig. S5A",
  "B_sph_decision_dist_to_sphere" =   "Fig. S5B left",
  "B_sph_decision_dist_to_spheroid" = "Fig. S5B right",
  "C_sph_buzz_time" =                 "Fig. S5C",
  "D_sph_buzz_range" =                "Fig. S5D",
  "sph_scan_combined" =               "Fig. S4"
)
```

```{r}
for (f in names(spheroid_AR_list)) {
  print(sprintf("Sheet %s: %s", f, spheroid_AR_list[[f]]))
  df = read.csv(file=paste(stat_path, spheroid_AR_list[[f]], sep="/")) %>%
    add_column(fig.panel = stat_spheroid_panel[[f]], .before = "position")
  spheroid_AR_list[[f]] = rename_estimate_ratio(df) %>%
    add_column("p.annotation" = apply(df["p.value"], MARGIN = 1, FUN = get_p_star))
}

df_all = bind_rows(spheroid_AR_list) %>%
  rename("Fig panel" = "fig.panel",
         "Position" = "position",
         "Contrast" = "contrast",
         "Estimate or ratio" = "estimate.or.ratio",
         "Lower CL" = "lower.CL",
         "Upper CL" = "upper.CL",
         "T ratio" = "t.ratio",
         "P value" = "p.value",
         "Fig annotation" = "p.annotation")

out_file = file.path(stat_path, "cmp_ARall_spheroid.xlsx")
write.xlsx(df_all, file = out_file)
print(sprintf("Outputs written to %s", out_file))
```






## Comparison over AR=1.3 clusters

### TC vs CT comparisons
```{r}
ar13_position_list = list(
  "last_scan_duration" =              "AR13_last_scan_duration_position_contrast.csv",
  "A_pos_decision_time" =             "AR13_A_decision_time_position_contrast.csv",
  "B_pos_decision_dist_sphere" =      "AR13_B1_decision_range_target_position_contrast.csv",
  "B_pos_decision_dist_spheroid" =    "AR13_B2_decision_range_clutter_position_contrast.csv",
  "C_pos_buzz_time" =                 "AR13_C_buzz_time_position_contrast.csv",
  "D_pos_buzz_range" =                "AR13_D_buzz_range_position_contrast.csv",
  "pos_scan_combined" =               "AR13_scan_combined_position_contrast.csv"
)
```

```{r}
for (f in names(ar13_position_list)) {
  print(sprintf("Sheet %s: %s", f, ar13_position_list[[f]]))
  df = read.csv(
    file=paste(stat_path, ar13_position_list[[f]], sep="/")
  )
  ar13_position_list[[f]] = rename_estimate_ratio(df) %>%
    add_column("p.annotation" = apply(df["p.value"], MARGIN = 1, FUN = get_p_star))
}

df_all = bind_rows(ar13_position_list) %>%
  add_column(
    fig.panel = c(
      "Fig. 6A", "Fig. S6A", "Fig. S6B left", "Fig. S6B right",
      "Fig. S6C", "Fig. S6D", "Fig. 6B"
    ),
    .before = "contrast"
  ) %>%
  rename("Fig panel" = "fig.panel",
         "Contrast" = "contrast",
         "Estimate or ratio" = "estimate.or.ratio",
         "Lower CL" = "lower.CL",
         "Upper CL" = "upper.CL",
         "T ratio" = "t.ratio",
         "P value" = "p.value",
         "Fig annotation" = "p.annotation",
         "Null" = "null")

out_file = file.path(stat_path, "cmp_AR13_position.xlsx")
write.xlsx(df_all, file = out_file)
print(sprintf("Outputs written to %s", out_file))
```


### Cluster comparisons
```{r}
ar13_cluster_list = list(
  "last_scan_duration" =              "AR13_last_scan_duration_cluster_contrast.csv",
  "A_clu_decision_time" =             "AR13_A_decision_time_cluster_contrast.csv",
  "B_clu_decision_dist_to_sphere" =   "AR13_B1_decision_range_target_cluster_contrast.csv",
  "B_clu_decision_dist_to_spheroid" = "AR13_B2_decision_range_clutter_cluster_contrast.csv",
  "C_clu_buzz_time" =                 "AR13_C_buzz_time_cluster_contrast.csv",
  "D_clu_buzz_range" =                "AR13_D_buzz_range_cluster_contrast.csv",
  "clu_scan_combined" =               "AR13_scan_combined_cluster_contrast.csv"
)
```

```{r}
ar13_cluster_panel = list(
  "last_scan_duration" =              "Fig. 6A",
  "A_clu_decision_time" =             "Fig. S6A",
  "B_clu_decision_dist_to_sphere" =   "Fig. S6B left",
  "B_clu_decision_dist_to_spheroid" = "Fig. S6B right",
  "C_clu_buzz_time" =                 "Fig. S6C",
  "D_clu_buzz_range" =                "Fig. S6D",
  "clu_scan_combined" =               "Fig. 6B"
)
```

```{r}
for (f in names(ar13_cluster_list)) {
  print(sprintf("Sheet %s: %s", f, ar13_cluster_list[[f]]))
  df = read.csv(file=paste(stat_path, ar13_cluster_list[[f]], sep="/")) %>%
    add_column(fig.panel = ar13_cluster_panel[[f]], .before = "position")
  ar13_cluster_list[[f]] = rename_estimate_ratio(df) %>%
    add_column("p.annotation" = apply(df["p.value"], MARGIN = 1, FUN = get_p_star))
}

df_all = bind_rows(ar13_cluster_list) %>%
  rename("Fig panel" = "fig.panel",
         "Contrast" = "contrast",
         "Position" = "position",
         "Estimate or ratio" = "estimate.or.ratio",
         "Lower CL" = "lower.CL",
         "Upper CL" = "upper.CL",
         "T ratio" = "t.ratio",
         "P value" = "p.value",
         "Fig annotation" = "p.annotation",
         "Null" = "null")

out_file = file.path(stat_path, "cmp_AR13_cluster.xlsx")
write.xlsx(df_all, file = out_file)
print(sprintf("Outputs written to %s", out_file))
```



## Session info
```{r}
sessionInfo()
```
