---
title: "AR=1.3 spheroid clusters comparison: time and range at buzz onset"
output: html_document
date: "`r Sys.Date()`"
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This notebook saves statistical results into different sheets of two excel files: one for comparisons across trials involving different spheroids, and the other for comparisons across AR=1.3 clusters.



## Load libraries
```{r}
library(openxlsx)
```


## Set up path
```{r}
main_path = "~/code_git/porpoise_spheroid"
stat_path = file.path(main_path, "stat")
```

## Save spheroid comparisons to an excel file
```{r}
stat_list = list(
  "A_pos_decision_time" =             "ARall_A_decision_time_position_contrast.csv",
  "B_pos_decision_dist_sphere" =      "ARall_B1_decision_range_target_position_contrast.csv",
  "B_pos_decision_dist_spheroid" =    "ARall_B2_decision_range_clutter_position_contrast.csv",
  "C_pos_buzz_time" =                 "ARall_C_buzz_time_position_contrast.csv",
  "D_pos_buzz_range" =                "ARall_D_buzz_range_position_contrast.csv",
  "E_pos_scan_to_sphere" =            "ARall_E_scan_ch0_position_contrast.csv",
  "F_pos_scan_to_spheroid" =          "ARall_F_scan_ch1_position_contrast.csv",
  "A_sph_decision_time" =             "ARall_A_decision_time_spheroid_contrast.csv",
  "B_sph_decision_dist_to_sphere" =   "ARall_B1_decision_range_target_spheroid_contrast.csv",
  "B_sph_decision_dist_to_spheroid" = "ARall_B2_decision_range_clutter_spheroid_contrast.csv",
  "C_sph_buzz_time" =                 "ARall_C_buzz_time_spheroid_contrast.csv",
  "D_sph_buzz_range" =                "ARall_D_buzz_range_spheroid_contrast.csv",
  "E_sph_scan_sphere" =               "ARall_E_scan_ch0_spheroid_contrast.csv",
  "F_sph_scan_spheroid" =             "ARall_F_scan_ch1_spheroid_contrast.csv"
)

for (f in names(stat_list)) {
  print(sprintf("Sheet %s: %s", f, stat_list[[f]]))
  stat_list[[f]] = read.csv(
    file=paste(stat_path, stat_list[[f]], sep="/")
  )
}

write.xlsx(stat_list, file = file.path(stat_path, "cmp_ARall.xlsx"))
```


## Save AR=1.3 cluster comparisons to an excel file
```{r}
stat_list = list(
  "A_pos_decision_time" =             "AR13_A_decision_time_position_contrast.csv",
  "B_pos_decision_dist_sphere" =      "AR13_B1_decision_range_target_position_contrast.csv",
  "B_pos_decision_dist_spheroid" =    "AR13_B2_decision_range_clutter_position_contrast.csv",
  "C_pos_buzz_time" =                 "AR13_C_buzz_time_position_contrast.csv",
  "D_pos_buzz_range" =                "AR13_D_buzz_range_position_contrast.csv",
  "E_pos_scan_to_sphere" =            "AR13_E_scan_ch0_position_contrast.csv",
  "F_pos_scan_to_spheroid" =          "AR13_F_scan_ch1_position_contrast.csv",
  "A_sph_decision_time" =             "AR13_A_decision_time_cluster_contrast.csv",
  "B_sph_decision_dist_to_sphere" =   "AR13_B1_decision_range_target_cluster_contrast.csv",
  "B_sph_decision_dist_to_spheroid" = "AR13_B2_decision_range_clutter_cluster_contrast.csv",
  "C_sph_buzz_time" =                 "AR13_C_buzz_time_cluster_contrast.csv",
  "D_sph_buzz_range" =                "AR13_D_buzz_range_cluster_contrast.csv",
  "E_sph_scan_sphere" =               "AR13_E_scan_ch0_cluster_contrast.csv",
  "F_sph_scan_spheroid" =             "AR13_F_scan_ch1_cluster_contrast.csv"
)

for (f in names(stat_list)) {
  print(sprintf("Sheet %s: %s", f, stat_list[[f]]))
  stat_list[[f]] = read.csv(
    file=paste(stat_path, stat_list[[f]], sep="/")
  )
}

write.xlsx(stat_list, file = file.path(stat_path, "cmp_AR13.xlsx"))
```


## Session info
```{r}
sessionInfo()
```
